"""association_id

Revision ID: 4f37e1b4a6aa
Revises: f8e53b866912
Create Date: 2022-03-14 17:23:08.986612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f37e1b4a6aa'
down_revision = 'f8e53b866912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('valvetothermostat', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('pumptovalve', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('outputtothermostatgroup', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('valvetothermostat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('pumptovalve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('outputtothermostatgroup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
