"""pump_cascade

Revision ID: f8e53b866912
Revises: 2fe347dff352
Create Date: 2022-03-09 16:35:39.757442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e53b866912'
down_revision = '2fe347dff352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pump', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pump_output_id_output', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_pump_output_id_output'), 'output', ['output_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pump', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pump_output_id_output'), type_='foreignkey')
        batch_op.create_foreign_key('fk_pump_output_id_output', 'output', ['output_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
